#!/usr/bin/python
#
# by Erik Osheim
#
# Use this to create HTML presentation files

template = """
<!DOCTYPE html>
<html>
  <head>
    <title>Title</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <style type="text/css">
      @import url(http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz);
      @import url(http://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic);
      @import url(http://fonts.googleapis.com/css?family=Ubuntu+Mono:400,700,400italic);

      body { font-family: 'Droid Serif'; }
      h1, h2, h3 {
        font-family: 'Yanone Kaffeesatz';
        font-weight: normal;
      }
      .remark-code, .remark-inline-code { font-family: 'Ubuntu Mono'; }
    </style>
  </head>
  <body>
    <textarea id="source">
%(markdown)s
    </textarea>
    <script src="http://gnab.github.io/remark/downloads/remark-latest.min.js" type="text/javascript">
    </script>
    <script type="text/javascript">
      var slideshow = remark.create();
    </script>
  </body>
</html>
"""

from os import listdir
from os.path import join, splitext

for name in listdir('slides'):
    base, _ = splitext(name)
    path = join('slides', name)
    target = join('html', base + '.html')

    print '%s -> %s' % (path, target)

    with open(path, 'r') as f:
        md = f.read()
    with open(target, 'w') as g:
        g.write(template % {'markdown': md})
